protected/controllers/AdminController.php
<?php
/**
 * AdminController Controller
 *
 */
//if (!isset($_SESSION)) { session_start(); }

class AdminController extends CController
{
	public $layout='admin_tpl';	
	public $crumbsTitle='';
	public $needs_db_update = false;
	
	/*public function accessRules()
	{				
	}
	
	public function filters()
	{		
	}
	*/
	public function beforeAction($action)
    {    	    	
    	$action_name = $action->id ;
    	//dump($action_name);
    	//$accept_controller=array('login','ajax','noaccessx');
    	$accept_controller=array('login');
	    if(!Yii::app()->functions->isAdminLogin() )
	    {
	    	if (!in_array($action_name,$accept_controller)){	    		
	    	   if ( Yii::app()->functions->has_session){
	    	   	    $message_out=t("You were logout because someone login with your account");
	    	   	    $this->redirect(array('admin/login/?message='.urlencode($message_out)));
	    	   } else $this->redirect(array('admin/login'));	           
	    	}
	    }
    	
	    $aa_access=Yii::app()->functions->AAccess();
	    $menu_list=Yii::app()->functions->AAmenuList();	    
	    	    
	    switch ($action_name) {
	    	case "viewemail":
	    		$action_name='emailogs';
	    		break;
	    
	    	case "merchantAdd":
	    	case "merchantadd":
	    		$action_name='merchant';
	    		break;
	    	default:
	    		break;
	    }
	    
	    $action_name=strtolower(trim($action_name));	 	    
	    
	    if (in_array($action_name,(array)$menu_list)){	    	
	    	if (!in_array($action_name,(array)$aa_access)){	 	    		
	    		$this->crumbsTitle  = t("Page not found");
	    		$this->render('error',array('msg'=>t("Sorry but you don't have permission to access this page")));
	    		Yii::app()->end();
	    	}
	    }
	    	    	    	    
	    return true;	    
    }
	
    public function init()
	{				
			
		 $name=Yii::app()->functions->getOptionAdmin('website_title');
		 if (!empty($name)){		 	
		 	 Yii::app()->name = $name;
		 }	
		 		 
		 // set website timezone
		 $website_timezone=Yii::app()->functions->getOptionAdmin("website_timezone");		 
		 if (!empty($website_timezone)){		 	
		 	Yii::app()->timeZone=$website_timezone;
		 }		 		

		 $ajax_admin=Yii::app()->createUrl('/ajaxadmin');
		 
		 $cs = Yii::app()->getClientScript();
		 $cs->registerScript(
		  'ajax_url',
		  "var ajax_url='$ajax_admin';",
		  CClientScript::POS_HEAD
		);
		
		$cs->registerScript(
		  'ajax_admin',
		  "var ajax_admin='$ajax_admin';",
		  CClientScript::POS_HEAD
		);		
		
		$admin_url = Yii::app()->createUrl('/admin');
		 $cs->registerScript(
		  'admin_url',
		  "var admin_url='$admin_url';",
		  CClientScript::POS_HEAD
		);
		
		$sites_url = Yii::app()->request->baseUrl;
		 $cs->registerScript(
		  'sites_url',
		  "var sites_url='$sites_url';",
		  CClientScript::POS_HEAD
		);
		
		$upload_url = Yii::app()->createUrl('/upload');
		 $cs->registerScript(
		  'upload_url',
		  "var upload_url='$upload_url';",
		  CClientScript::POS_HEAD
		);
						 
		FunctionsV3::handleLanguage();
		$lang=Yii::app()->language;		
		$cs->registerScript(
		  'lang',
		  "var lang='$lang';",
		  CClientScript::POS_HEAD
		);
		
		$order_notification=getOptionA('admin_disabled_order_notification');
		$cs->registerScript(
		  'order_notification',
		  "var order_notification='$order_notification';",
		  CClientScript::POS_HEAD
		);
		
		$order_notification_sounds=getOptionA('admin_disabled_order_notification_sounds');
		$cs->registerScript(
		  'order_notification_sounds',
		  "var order_notification_sounds='$order_notification_sounds';",
		  CClientScript::POS_HEAD
		);
		
		/*ADD SECURITY VALIDATION*/
		$yii_session_token=session_id();		
		$cs->registerScript(
		  'yii_session_token',
		 "var yii_session_token='$yii_session_token';",
		  CClientScript::POS_HEAD
		);				
		
		$csrfTokenName = Yii::app()->request->csrfTokenName;
        $csrfToken = Yii::app()->request->csrfToken;        
        
		$cs->registerScript(
		  "$csrfTokenName",
		 "var $csrfTokenName='$csrfToken';",
		  CClientScript::POS_HEAD
		);
		
		$image_limit_size = FunctionsV3::imageLimitSize();
		
		$cs->registerScript(
		  'image_limit_size',
		 "var image_limit_size='$image_limit_size';",
		  CClientScript::POS_HEAD
		);	
		
		$cs->registerScript(
		  'current_panel',
		 "var current_panel='admin';",
		  CClientScript::POS_HEAD
		);		

		$is_login = false;
		if(Yii::app()->functions->isAdminLogin() ){
			$is_login=true;
		}
		
		$cs->registerScript(
		  'has_session',
		 "var has_session='$is_login';",
		  CClientScript::POS_HEAD
		);		
		
	}
	
	public function actionDashboard()
	{
		if ( !Yii::app()->functions->isAdminLogin()){			
			$this->layout='login_tpl';
			$this->render('login');
		} else {						
			
			if(FunctionsV3::checkNewDb()){					
			   $this->needs_db_update = true;
			}
				
			$this->crumbsTitle=Yii::t("default","Dashboard");		
			$this->render('dashboard');			
		}		
	}
				  
	public function actionIndex()
	{					
		if ( !Yii::app()->functions->isAdminLogin()){			
			$this->layout='login_tpl';
			$this->render('login');
		} else {						
			$aa_access=Yii::app()->functions->AAccess();
			if (in_array('dashboard',(array)$aa_access)){
				
				if(FunctionsV3::checkNewDb()){					
					$this->needs_db_update = true;
				}
								
				$this->crumbsTitle=Yii::t("default","Dashboard");		
				$this->render('dashboard');			
			} else $this->render('error',array('msg'=>t("Sorry but you don't have access to dashboard")));			
		}		
	}	
	
	public function actionLogin()
	{		
		if (isset($_GET['logout'])){
			//Yii::app()->request->cookies['kr_user'] = new CHttpCookie('kr_user', ""); 			
			//Yii::app()->request->cookies['kr_admin_lang_id'] = new CHttpCookie('kr_admin_lang_id', ""); 			
			unset($_SESSION['kr_user']);
			unset($_SESSION['kr_user_session']);
		}		
		$this->layout='login_tpl';
	    $this->render('login');
	}
	

	public function actionMerchant()
	{
		$this->crumbsTitle=Yii::t("default","Merchant");
		$this->render('merchant-list');
	}
	
	public function actionMerchantAdd()
	{
		$tags =   (array)FunctionsV3::dropdownFormat(
		   FunctionsV3::getTags(),'tag_id','tag_name'
		);
		
		$this->crumbsTitle=Yii::t("default","Merchant Add");
		$this->render('merchant-add',array(
		 'tags'=>$tags
		));
	}
	
	public function actionPackages()
	{		
		if (isset($_GET['Do'])){
		   $this->crumbsTitle=Yii::t("default","Packages Sort");
		   $this->render('packages-sort');
		} else {
		   $this->crumbsTitle=Yii::t("default","Packages");
		   $this->render('packages-list');
		}
	}
	
	public function actionPackagesAdd()
	{
		$this->crumbsTitle=Yii::t("default","Packages add");
		$this->render('packages-add');
	}
	
	public function actionPaypalSettings()
	{
		$this->crumbsTitle=Yii::t("default","Paypal Settings");
		$this->render('paypal-settings');
	}
	
	public function actionSettings()
	{
		$this->crumbsTitle=Yii::t("default","Settings");
		$this->render('settings-new',array(
		 'status_list'=>Yii::app()->functions->orderStatusList2(true),
		 'cancel_order_status'=>getOptionA('cancel_order_status_accepted'),
		 'restrict_order_by_status'=>getOptionA('restrict_order_by_status')
		));
	}
	
	public function actionRptMerchantReg()
	{
		$this->crumbsTitle=Yii::t("default","Merchant Registration");
		$this->render('rpt-merchant-reg');
	}
	
	public function actionRptMerchantPayment()
	{
		$this->crumbsTitle=Yii::t("default","Merchant Payment");
		$this->render('rpt-merchant-payment');
	}
	
	public function actionSponsoredMerchantList()
	{
		if (isset($_GET['Do'])){
			$this->crumbsTitle=Yii::t("default","Sponsored Merchant Add");
		    $this->render('sponsored-merchant-add');
		} else {
		    $this->crumbsTitle=Yii::t("default","Sponsored Merchant List");
		    $this->render('sponsored-merchant');	
		}		
	}	
	
	public function actionManageCurrency()
	{
		if (isset($_GET['Do'])){
			$this->crumbsTitle=Yii::t("default","Currency Add");
		    $this->render('currency-list-add');
		} else {
		    $this->crumbsTitle=Yii::t("default","Currency List");
		    $this->render('currency-list');	
		}		
	}
	
	public function actionCuisine()
	{
	   if (isset($_GET['Do'])){
	   	   if ($_GET['Do']=="Add"){
			   $this->crumbsTitle=Yii::t("default","Cuisine Add");
		       $this->render('cuisine-add');
	   	   } else {
	   	   	   $this->crumbsTitle=Yii::t("default","Cuisine Sort");
		       $this->render('cuisine-sort');
	   	   }
		} else {
		    $this->crumbsTitle=Yii::t("default","Cuisine List");
		    $this->render('cuisine-list');	
		}		
	}
	
	public function actionOrderStatus()
	{
		if (isset($_GET['Do'])){
	   	   if ($_GET['Do']=="Add"){
			   $this->crumbsTitle=Yii::t("default","Order Status Add");
		       $this->render('order-status-add');
	   	   }   	   	   
		} else {
		    $this->crumbsTitle=Yii::t("default","Order Status List");
		    $this->render('order-status-list');	
		}		
	}
	
	public function actionContactSettings()
	{
		$this->crumbsTitle=Yii::t("default","Contact Settings");
		$this->render('contact-settings');
	}
	
	public function actionSocialSettings()
	{
		$this->crumbsTitle=Yii::t("default","Social Settings");
		$this->render('social-settings');
	}
	
	public function actionRatings()
	{
		if (isset($_GET['Do'])){
			$this->crumbsTitle=Yii::t("default","Ratings Add");
		   $this->render('ratings-add');
		} else {
	       $this->crumbsTitle=Yii::t("default","Ratings");
		   $this->render('ratings');
		}
	}
	
	public function actionProfile()
	{
		$this->crumbsTitle=Yii::t("default","Profile Settings");
		$this->render('profile');
	}
	
	public function actionUserList()
	{
		
		if (isset($_GET['Do'])){
			$this->crumbsTitle=Yii::t("default","User Add");
		    $this->render('user-add');
		} else {
		    $this->crumbsTitle=Yii::t("default","User List");
		    $this->render('user-list');
		}
	}
	
	public function actionCustomPage()
	{
		if (isset($_GET['Do'])){
			if ($_GET['Do']=="Add"){
				
			   $data = array();
			   if(isset($_GET['id'])){

protected/views/admin/bankdeposit-list.php
<form id="frm_table_list" method="POST" >
<input type="hidden" name="action" id="action" value="BankDepositList">
<input type="hidden" name="tbl" id="tbl" value="bank_deposit">
<input type="hidden" name="clear_tbl"  id="clear_tbl" value="clear_tbl">
<input type="hidden" name="whereid"  id="whereid" value="id">
<input type="hidden" name="slug" id="slug" value="bankdeposit">
<table id="table_list" class="uk-table uk-table-hover uk-table-striped uk-table-condensed"> 
   <thead>
        <tr>
            <th width="3%"><?php echo Yii::t("default","ID")?></th>
            <th width="7%"><?php echo Yii::t("default","TransType")?></th>
            <th width="7%"><?php echo Yii::t("default","Merchant Name")?></th>
            <th width="7%"><?php echo Yii::t("default","Branch Code")?></th>
            <th width="7%"><?php echo Yii::t("default","Date")?></th>
            <th width="7%"><?php echo Yii::t("default","Time")?></th>
            <th width="7%"><?php echo Yii::t("default","Amount")?></th>
            <th width="7%"><?php echo Yii::t("default","Scan Bank deposit slip")?></th>
            <th width="5%"><?php echo Yii::t("default","Date Created")?></th>            
        </tr>
    </thead>
    <tbody>    
    </tbody>
</table>
<div class="clear"></div>
</form>

protected/views/admin/cancel_order.php
<form id="frm_table_list2" method="POST" class="report uk-form uk-form-horizontal merchant-dashboard" >
<input type="hidden" name="action" id="action" value="requestCancelOrderList">
<input type="hidden" name="tbl" id="tbl" value="item">
<table id="table_list2" class="uk-table uk-table-hover uk-table-striped uk-table-condensed">  
   <thead>
        <tr> 
            <th width="2%"><?php echo Yii::t('default',"Ref#")?></th>
            <th width="6%"><?php echo Yii::t('default',"Name")?></th>
            <th width="6%"><?php echo Yii::t('default',"Contact#")?></th>
            <th width="3%"><?php echo Yii::t('default',"Item")?></th>            
            <th width="3%"><?php echo Yii::t('default',"TransType")?></th>
            <th width="3%"><?php echo Yii::t('default',"Payment Type")?></th>
            <th width="3%"><?php echo Yii::t('default',"Total")?></th>
            <th width="3%"><?php echo Yii::t('default',"Tax")?></th>
            <th width="3%"><?php echo Yii::t('default',"Total W/Tax")?></th>
            <th width="3%"><?php echo Yii::t('default',"Status")?></th>
            <th width="3%"><?php echo Yii::t('default',"Platform")?></th>
            <th width="3%"><?php echo Yii::t('default',"Date")?></th>
            <th width="3%"></th>
        </tr>
    </thead>
    <tbody>    
    </tbody>
</table>
</form>

protected/views/admin/category-add.php
<div class="uk-width-1">
<a href="<?php echo Yii::app()->request->baseUrl; ?>/admin/category/do/add" class="uk-button"><i class="fa fa-plus"></i> <?php echo Yii::t("default","Add New")?></a>
<a href="<?php echo Yii::app()->request->baseUrl; ?>/admin/category" class="uk-button"><i class="fa fa-list"></i> <?php echo Yii::t("default","List")?></a>

<a href="<?php echo Yii::app()->request->baseUrl; ?>/admin/categorysettings" class="uk-button"><i class="fa fa-list"></i> <?php echo Yii::t("default","Settings")?></a>

</div>

<div class="spacer"></div>

<div id="error-message-wrapper"></div>

<form class="uk-form uk-form-horizontal forms" id="forms">
<?php echo CHtml::hiddenField('action','adminAddCategory')?>
<?php echo CHtml::hiddenField('id',isset($_GET['id'])?$_GET['id']:"");?>
<?php if (!isset($_GET['id'])):?>
<?php echo CHtml::hiddenField("redirect",Yii::app()->request->baseUrl."/admin/category/do/add")?>
<?php endif;?>

<?php 
if (isset($_GET['id'])){
	if (!$data=Yii::app()->functions->getCategory($_GET['id'])){
		echo "<div class=\"uk-alert uk-alert-danger\">".
		Yii::t("default","Sorry but we cannot find what your are looking for.")."</div>";
		return ;
	}	
}
?>                                 

<div class="uk-form-row">

<?php if ( Yii::app()->functions->multipleField()==2):?>

<ul data-uk-tab="{connect:'#tab-content'}" class="uk-tab uk-active">
    <li class="uk-active" ><a href="#"><?php echo t("English")?></a></li>
    <?php if ( $fields=Yii::app()->functions->getLanguageField()):?>  
    <?php foreach ($fields as $f_val): ?>
    <li class="" ><a href="#"><?php echo $f_val;?></a></li>
    <?php endforeach;?>
    <?php endif;?>
</ul>

<ul class="uk-switcher" id="tab-content">

  <li class="uk-active">      
  <div class="uk-form-row">
   <label class="uk-form-label"><?php echo Yii::t("default","Food Category Name")?></label>
  <?php echo CHtml::textField('category_name',
  isset($data['category_name'])?stripslashes($data['category_name']):""
  ,array(
  'class'=>'uk-form-width-large',
  'data-validation'=>"required"
  ))?>  
    </div>    
    
  <div class="uk-form-row">
  <label class="uk-form-label"><?php echo Yii::t("default","Description")?></label>
  <?php echo CHtml::textField('category_description',
  isset($data['category_description'])?stripslashes($data['category_description']):""
  ,array(
  'class'=>'uk-form-width-large',
  ))?>
  </div>   
   </li>
   
   <?php 
   $category_name_trans=isset($data['category_name_trans'])?json_decode($data['category_name_trans'],true):'';   
   $category_description_trans=isset($data['category_description_trans'])?json_decode($data['category_description_trans'],true):'';   
   ?>
   
   <?php if (is_array($fields) && count($fields)>=1):?>
   <?php foreach ($fields as $key_f => $f_val): ?>
   <li>
   
   <div class="uk-form-row">
	   <label class="uk-form-label"><?php echo Yii::t("default","Food Category Name")?></label>
	  <?php echo CHtml::textField("category_name_trans[$key_f]",
	  array_key_exists($key_f,(array)$category_name_trans)?$category_name_trans[$key_f]:''
	  ,array(
	  'class'=>'uk-form-width-large',
	  //'data-validation'=>"required"
	  ))?>  
   </div>    
   
   <div class="uk-form-row">
	  <label class="uk-form-label"><?php echo Yii::t("default","Description")?></label>
	  <?php echo CHtml::textField("category_description_trans[$key_f]",
	  array_key_exists($key_f,(array)$category_description_trans)?$category_description_trans[$key_f]:''
	  ,array(
	  'class'=>'uk-form-width-large',
	  ))?>
  </div>   
   
   </li>
   <?php endforeach;?>
   <?php endif;?>
</ul>

<?php else : // Normal field?>

<div class="uk-form-row">
<label class="uk-form-label"><?php echo Yii::t("default","Food Category Name")?></label>
  <?php echo CHtml::textField('category_name',
  isset($data['category_name'])?stripslashes($data['category_name']):""
  ,array(
  'class'=>'uk-form-width-large',
  'data-validation'=>"required"
  ))?>  
</div>

<div class="uk-form-row">
  <label class="uk-form-label"><?php echo Yii::t("default","Description")?></label>
  <?php echo CHtml::textField('category_description',
  isset($data['category_description'])?stripslashes($data['category_description']):""
  ,array(
  'class'=>'uk-form-width-large',
  ))?>
</div>

<?php endif;?>

<div class="uk-form-row"> 
 <label class="uk-form-label"><?php echo Yii::t('default',"Featured Image")?></label>
  <div style="display:inline-table;margin-left:1px;" class="button uk-button" id="photo"><?php echo Yii::t('default',"Browse")?></div>	  
  <DIV  style="display:none;" class="photo_chart_status" >
	<div id="percent_bar" class="photo_percent_bar"></div>
	<div id="progress_bar" class="photo_progress_bar">
	  <div id="status_bar" class="photo_status_bar"></div>
	</div>
  </DIV>		  
</div>

<?php if (!empty($data['photo'])):?>
<div class="uk-form-row"> 
<?php else :?>
<div class="input_block preview">
<?php endif;?>
<label><?php echo Yii::t('default',"Preview")?></label>
<div class="image_preview">
 <?php if (!empty($data['photo'])):?>
 <input type="hidden" name="photo" value="<?php echo $data['photo'];?>">
 <img class="uk-thumbnail uk-thumbnail-small" src="<?php echo Yii::app()->request->baseUrl."/upload/".$data['photo'];?>?>" alt="" title="">
 <?php endif;?>
</div>
</div>


<?php $dish=Yii::app()->functions->GetDishList();?>
<?php $dish_selected=isset($data['dish'])?json_decode($data['dish'],true):'';?>
<?php if (is_array($dish) && count($dish)>=1):?>
  <div class="uk-form-row">
  <label class="uk-form-label uk-h3"><?php echo Yii::t("default","Dish")?></label>  
  <div class="clear"></div>
  <ul class="uk-list uk-list-striped">
  
  <?php foreach ($dish as $dish_val):?>
  <li>
  <?php echo CHtml::checkBox('dish[]',
  in_array($dish_val['dish_id'],(array)$dish_selected)?true:false
  ,array(
   'class'=>"icheck",
   'value'=>$dish_val['dish_id']
  ))?>	  
  <?php echo $dish_val['dish_name']?>
  <?php endforeach;?>
  
  </li>
  </ul>
</div>
<?php endif;?>

<!--<div class="uk-form-row">
  <label class="uk-form-label"><?php echo t("Spicy Note")?></label>
  <?php 
  echo CHtml::textArea('spicydish_notes',$data['spicydish_notes'],array(
    'class'=>"big-textarea"
  ))
  ?>
</div>-->

<div class="uk-form-row">
  <label class="uk-form-label"><?php echo t("Status")?></label>
  <?php echo CHtml::dropDownList('status',
  isset($data['status'])?$data['status']:"",
  (array)statusList(),          
  array(
  'class'=>'uk-form-width-large',
  'data-validation'=>"required"
  ))?>
</div>

<div class="uk-form-row">
<label class="uk-form-label"></label>
<input type="submit" value="<?php echo Yii::t("default","Save")?>" class="uk-button uk-form-width-medium uk-button-success">
</div>

</form>

protected/views/admin/dishes-list.php
<div class="uk-width-1">
<a href="<?php echo Yii::app()->request->baseUrl; ?>/admin/dishes/Do/Add" class="uk-button"><i class="fa fa-plus"></i> <?php echo Yii::t("default","Add New")?></a>

<a href="<?php echo Yii::app()->request->baseUrl; ?>/admin/dishes" class="uk-button"><i class="fa fa-list"></i> <?php echo Yii::t("default","List")?></a>

</div>

<form id="frm_table_list" method="POST" >
<input type="hidden" name="action" id="action" value="dishList">
<input type="hidden" name="tbl" id="tbl" value="dishes">
<input type="hidden" name="clear_tbl"  id="clear_tbl" value="clear_tbl">
<input type="hidden" name="whereid"  id="whereid" value="dish_id">
<input type="hidden" name="slug" id="slug" value="/admin/dishes/Do/Add">
<table id="table_list" class="uk-table uk-table-hover uk-table-striped uk-table-condensed">  
   <thead>
        <tr>
            <th width="2%"><?php echo Yii::t("default","ID")?></th>
            <th width="7%"><?php echo Yii::t("default","Dish Name")?></th>
            <th width="6%"><?php echo Yii::t("default","Icon")?></th>            
            <th width="3%"><?php echo Yii::t("default","Date Created")?></th>            
        </tr>
    </thead>
    <tbody>    
    </tbody>
</table>
<div class="clear"></div>
</form>

protected/views/admin/error.php
<p class="uk-text-danger">
<i style="color:red;" class="fa fa-exclamation-triangle"></i> <?php echo $msg?>
</p>

protected/views/admin/fax-package-list.php
<div class="uk-width-1">
<a href="<?php echo Yii::app()->request->baseUrl; ?>/admin/faxpackage/Do/Add" class="uk-button"><i class="fa fa-plus"></i> <?php echo Yii::t("default","Add New")?></a>
<a href="<?php echo Yii::app()->request->baseUrl; ?>/admin/faxpackage" class="uk-button"><i class="fa fa-list"></i> <?php echo Yii::t("default","List")?></a>

<a href="<?php echo Yii::app()->request->baseUrl; ?>/admin/faxpackage/Do/Sort" class="uk-button"><i class="fa fa-sort-alpha-asc"></i> <?php echo Yii::t("default","Sort")?></a>
</div>

<form id="frm_table_list" method="POST" >
<input type="hidden" name="action" id="action" value="FaxpackagesList">
<input type="hidden" name="tbl" id="tbl" value="fax_package">
<input type="hidden" name="clear_tbl"  id="clear_tbl" value="clear_tbl">
<input type="hidden" name="whereid"  id="whereid" value="fax_package_id">
<input type="hidden" name="slug" id="slug" value="faxpackage/Do/Add">
<table id="table_list" class="uk-table uk-table-hover uk-table-striped uk-table-condensed">
  <!--<caption>Merchant List</caption>-->
   <thead>
        <tr>
            <th width="3%"><?php echo Yii::t("default","ID")?></th>
            <th width="7%"><?php echo Yii::t("default","Title")?></th>
            <th width="7%"><?php echo Yii::t("default","Description")?></th>
            <th width="3%"><?php echo Yii::t("default","Price")?></th>
            <th width="3%"><?php echo Yii::t("default","Promo Price")?></th>
            <th width="5%"><?php echo Yii::t("default","Fax Credit Limit")?></th>            
            <th width="5%"><?php echo Yii::t("default","Status")?></th>            
        </tr>
    </thead>
    <tbody>    
    </tbody>
</table>
<div class="clear"></div>
</form>

protected/views/admin/order-status-list.php
<div class="uk-width-1">
<a href="<?php echo Yii::app()->request->baseUrl; ?>/admin/OrderStatus/Do/Add" class="uk-button"><i class="fa fa-plus"></i> <?php echo Yii::t("default","Add New")?></a>
<a href="<?php echo Yii::app()->request->baseUrl; ?>/admin/OrderStatus" class="uk-button"><i class="fa fa-list"></i> <?php echo Yii::t("default","List")?></a>
</div>

<form id="frm_table_list" method="POST" >
<input type="hidden" name="action" id="action" value="OrderStatusList">
<input type="hidden" name="tbl" id="tbl" value="order_status">
<input type="hidden" name="clear_tbl"  id="clear_tbl" value="clear_tbl">
<input type="hidden" name="whereid"  id="whereid" value="stats_id">
<input type="hidden" name="slug" id="slug" value="OrderStatus/Do/Add">
<table id="table_list" class="uk-table uk-table-hover uk-table-striped uk-table-condensed">
  <!--<caption>Merchant List</caption>-->
   <thead>
        <tr>            
            <th width="5%"><?php echo Yii::t('default',"ID")?></th>
            <th width="4%"><?php echo Yii::t('default',"Status")?></th>            
            <th width="4%"><?php echo Yii::t('default',"Date")?></th>
        </tr>
    </thead>
    <tbody>    
    </tbody>
</table>
<div class="clear"></div>
</form>

protected/views/admin/test_map.php
<H2><?php echo t("Geocoding results")?></H2>

<p>
<?php 
dump($geocode);
?>
</p>

<h2><?php echo t("Map results")?></h2>
<?php if($provider=="google.maps"):?>
<p class="uk-text-muted"><?php echo t("If you cannot see the map or the map says This page can't load Google Maps correctly below it means your api is not working, enabled the api Google Maps JavaScript API")?></p>
<?php else :?>
<p class="uk-text-muted"><?php echo t("If you cannot see the map below it means your api key is not working")?>.</p>
<?php endif;?>

<div class="test_map" id="test_map">
</div>

<p>
<a  href="<?php echo Yii::app()->createUrl("admin/settings")?>"><?php echo t("Go back")?></a>
</p>